version: '3.8'

services:
  appointment-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - appointment-data:/var/lib/postgresql/data
      - ./ddl/appointment.sql:/docker-entrypoint-initdb.d/appointment.sql
    environment:
      POSTGRES_DB: appointmentdb
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: test2024!
    restart: always

  auth-db:
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
      - ./ddl/auth.sql:/docker-entrypoint-initdb.d/auth.sql
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: test2024!
    restart: always

  profileportal-api:
    build: ./profileportal
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: server
    depends_on:
      - appointment-db
      - auth-db
    restart: always

volumes:
  appointment-data:
  auth-data:
