version: '3.8'

services:
  appointment-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - appointment-data:/var/lib/postgresql/data
      - ./ddl/appointment.sql:/docker-entrypoint-initdb.d/appointment.sql
    environment:
      POSTGRES_DB: appointmentdb
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: test2024!
    restart: always

  auth-db:
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
      - ./ddl/auth.sql:/docker-entrypoint-initdb.d/auth.sql
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: test2024!
    restart: always

  # profileportal-api:
  #   build: ./path/to/your/profileportal-api
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     APPOINTMENT_DATABASE_URL: postgres://dbadmin:test2024!@appointment-db:5432/appointmentdb
  #     AUTH_DATABASE_URL: postgres://dbadmin:test2024!@auth-db:5432/authdb
  #   depends_on:
  #     - appointment-db
  #     - auth-db
  #   restart: always

  # rbac-api:
  #   build: ./path/to/your/rbac-api
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     AUTH_DATABASE_URL: postgres://dbadmin:test2024!@auth-db:5432/authdb
  #   depends_on:
  #     - auth-db
  #   restart: always

volumes:
  appointment-data:
  auth-data:
